server:
  port: 5503
  host: localhost
auth:
  jwksUri: http://localhost:5501/.well-known/jwks.json
database:
  url: mongodb+srv://nareshsuthar1229:rmBlTHTRnZMlIa8v@cluster0.lb8ejo0.mongodb.net/order-service?authSource=admin&w=1
